---
- hosts: appserver #groups name in inventory
  become: yes  #to do installation you need yes
  tasks:
  - name: install openjdk 8
    apt: 
      name: openjdk-8-jdk
      state: present #will install 
  - name: install tomcat 9
    apt:
     name: tomcat9
     state: present #will install
  - name: download jenkins to webapps/
    get_url:
https://prodjenkinsreleases.blob.core.windows.net/debian-stable/jenkins_2.176.2_all.deb
      destination: /var/lib/tomcat9/webapps/jenkins_2.176.2_all.deb


  - name: enable and start tomcat
    service: #to start service
      name: tomcat
      state: started # to start
      enabled : yes

      #take manual steps to create application and search for module for it from ansible
